### ISSUE TITLE
Any news on PHP7 support?

### ISSUE THREAD

**Issue by gabel** [techpivot/phalcon-ci-installer#2]
Are there any plans for upcoming PHP7 support?

**Comment by virgofx** [comment]
Yeah I'll incorporate that hopefully very soon. There's just a little more complication to cache the right elements so future builds will be fast when dealing with Zephir :)

**Comment by gabel** [comment]
Thx for the feedback.

Caching... I am dreaming of caching with a travis-ci instance without caching enabled. :sweat: :blush:

**Comment by virgofx** [comment]
@gabel Phalcon 2.1.x with PHP7 is now supported. See readme for more info. Happy testing. Let me know if you experience any issues.

**Comment by gabel** [comment]
Thx for the work.. I've noticed one problem in our constellation as we use `phalcon/incubator` which requires `ext_phalcon` in our `composer.json`. Therefore the installation of `ext_phalcon` have to run before `composer install` but `phalcon/zephir` is needed in the first step to build `ext_phalcon` which would be installed by... yes you're right `composer install`. 

I think we will get `phalcon/zephir` separatly.

**Comment by virgofx** [comment]
Gabel -- good point and thanks for the test. Let me investigate and I'll keep you posted.

**Comment by gabel** [comment]
@virgofx Got a workaround so far..

composer.json

``` json
{
    "name": "some/package",
    "description": "some package",
    "require": {
        "phalcon/incubator": "dev-master",
    },
    "require-dev": {
        "techpivot/phalcon-ci-installer": "^1.0"
    },
    "config": {
        "bin-dir": "bin/"
    }
}
```

.travis.yml the `--ignore-platform-reqs` works... this may not be the best solution at all, as all platform reqs are ignored, but it works in my case..

``` yml
language: php

php:
  - 7.0

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer self-update
  - composer install --prefer-source --no-interaction --ignore-platform-reqs
  - ./bin/install-phalcon.sh 2.1.x

script:
  - php -r "echo \Phalcon\Version::get();"

notifications:
  email: false
```
